(function(){
  const $=id=>document.getElementById(id);let account={configured:false,user:null},projects=[],editing=null;
  const accountModal=$('accountModal'),memoryModal=$('memoryModal');
  document.querySelector('.app').inert=true;document.body.classList.add('auth-visible');
  let activeModel=null,renderedOwner=null,googleWaiting=false,sendAfter=0,authMode='signin',confirmation=false;
  const busy=new Set();
  function updateAuthControls(){const remaining=Math.max(0,Math.ceil((sendAfter-Date.now())/1000));const working=busy.size>0;$('accountGoogle').disabled=!account.configured||working;$('accountGoogle').lastChild.textContent=googleWaiting?'Cancel Google sign-in':'Continue with Google';$('accountSubmit').disabled=!account.configured||working;$('accountSubmit').textContent=busy.has('accountSubmit')?'Please wait…':authMode==='signup'?'Create account':'Sign in';$('accountSwitchMode').disabled=working;$('accountSwitchMode').textContent=authMode==='signup'?'Already have an account? Sign in':'Create an account';$('loginPassword').autocomplete=authMode==='signup'?'new-password':'current-password';$('loginPassword').minLength=authMode==='signup'?8:1;$('accountSendCode').disabled=!account.configured||remaining>0||working;$('accountSendCode').textContent=busy.has('accountSendCode')?'Sending code…':remaining?'Try again in '+remaining+'s':'Use an email code instead';$('accountResend').disabled=!account.configured||remaining>0||working;$('accountResend').textContent=remaining?'Resend in '+remaining+'s':'Resend code';$('accountVerifyCode').disabled=!account.configured||working;}
  const authClock=setInterval(updateAuthControls,1000);window.addEventListener('beforeunload',()=>clearInterval(authClock));
  const consent=document.createElement('label'),useMemory=document.createElement('input'),consentText=document.createElement('span');
  useMemory.type='checkbox';useMemory.id='useSavedMemory';consent.className='preset-consent';consent.append(useMemory,consentText);$('memoryScopeNote').after(consent);
  consentText.textContent='Choose a model before enabling presets in chats.';useMemory.disabled=true;
  function close(modal){modal.classList.remove('show');if(modal===accountModal){document.querySelector('.app').inert=false;document.body.classList.remove('auth-visible');$('userInput').focus();}else $('profileBtn').focus();}
  function openAccount(startup=false){$('openMemory').hidden=!account.user;accountModal.classList.add('show');document.querySelector('.app').inert=true;document.body.classList.add('auth-visible');(account.user?$('openMemory'):$('loginEmail')).focus();}
  for(const [modal,button] of [[accountModal,$('accountClose')],[memoryModal,$('memoryClose')]]){button.onclick=()=>close(modal);modal.addEventListener('click',e=>{if(e.target===modal&&modal!==accountModal)close(modal);});modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close(modal);}if(e.key==='Tab'){const controls=[...modal.querySelectorAll('button,input,textarea,select')].filter(el=>!el.disabled&&el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});}
  function render(){
    const owner=account.user?.id||'local';if(renderedOwner!==owner){useMemory.checked=false;renderedOwner=owner;editing=null;$('memoryText').value='';$('memoryList').replaceChildren();if(memoryModal.classList.contains('show'))renderMemory().catch(e=>{$('memoryError').textContent=e.message;});}
    $('profileName').textContent=account.user?.email||'Local profile';$('profileStatus').textContent=account.user?'Signed in':'Presets & account';
    $('accountSignedOut').hidden=!!account.user;$('accountSignedIn').hidden=!account.user;
    $('accountEmail').textContent=account.user?.email||'';
    $('openMemory').textContent='Presets';
    $('accountSetupNote').hidden=account.configured;
    updateAuthControls();
    $('accountClose').innerHTML=account.user?'Back to workspace <span aria-hidden="true">→</span>':'Continue without an account <span aria-hidden="true">→</span>';
    $('accountFootnote').hidden=!!account.user;
    $('memorySync').disabled=!account.user;
    $('memoryScopeNote').textContent='Set the tone, language, length, and style of answers across your chats.';renderAvatar();$('profileSignOut').hidden=!account.user;
  }
  async function refresh(){if(window.api?.accountStatus)account=await window.api.accountStatus();render();}
  async function action(button,fn){if(busy.size)return;busy.add(button.id);updateAuthControls();$('accountError').textContent='';try{await fn();}catch(e){$('accountError').textContent=e.message;}finally{busy.delete(button.id);button.disabled=false;render();}}
  function avatarKey(){return 'multimind.avatar.'+(account.user?.id||'local');}
  function renderAvatar(){const avatar=$('profileAvatar');avatar.replaceChildren();const stored=localStorage.getItem(avatarKey());if(stored&&/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(stored)){const image=document.createElement('img');image.src=stored;image.alt='Your avatar';avatar.append(image);}else avatar.textContent=Array.from(account.user?.email||'Local')[0].toUpperCase();}
  function closeProfile(){$('profileMenu').hidden=true;$('profileBtn').setAttribute('aria-expanded','false');}
  const appElement=document.querySelector('.app');
  function syncProfileSidebar(){const collapsed=appElement.classList.contains('tab-collapsed');$('profileBtn').disabled=collapsed;if(collapsed)closeProfile();}
  const profileSidebarObserver=new MutationObserver(syncProfileSidebar);profileSidebarObserver.observe(appElement,{attributes:true,attributeFilter:['class']});syncProfileSidebar();window.addEventListener('beforeunload',()=>profileSidebarObserver.disconnect());
  $('profileBtn').onclick=async()=>{if(appElement.classList.contains('tab-collapsed'))return;const opening=$('profileMenu').hidden;await refresh();if(appElement.classList.contains('tab-collapsed')){closeProfile();return;}if(!account.user){closeProfile();openAccount();return;}$('profileMenu').hidden=!opening;$('profileBtn').setAttribute('aria-expanded',String(opening));};
  document.addEventListener('click',e=>{if(!e.target.closest('#profileBtn,#profileMenu'))closeProfile();});
  $('profileMenu').addEventListener('keydown',e=>{if(e.key==='Escape'){closeProfile();$('profileBtn').focus();}});
  $('profileAccount').onclick=()=>{closeProfile();openAccount();};
  $('profilePresets').onclick=()=>{closeProfile();$('openMemory').click();};
  $('profileSignOut').onclick=async()=>{closeProfile();await action($('profileSignOut'),async()=>{account=await window.api.accountLogout();render();});};
  $('profileChangeAvatar').onclick=()=>{closeProfile();$('profileAvatarFile').click();};
  $('profileResetAvatar').onclick=()=>{localStorage.removeItem(avatarKey());renderAvatar();closeProfile();};
  $('profileAvatarFile').onchange=async e=>{const file=e.target.files[0],key=avatarKey();e.target.value='';if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Choose a PNG, JPEG or WebP image under 5 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const size=Math.min(bitmap.width,bitmap.height);canvas.getContext('2d').drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,128,128);bitmap.close();if(key!==avatarKey())return;localStorage.setItem(key,canvas.toDataURL('image/png'));renderAvatar();}catch(error){openAccount();$('accountError').textContent=error.message;}};
  $('accountGoogle').onclick=()=>action($('accountGoogle'),async()=>{if(googleWaiting){await window.api.accountCancel();googleWaiting=false;}else{await window.api.accountGoogle();googleWaiting=true;}$('accountCancel').hidden=true;});
  $('accountCancel').onclick=async()=>{await window.api.accountCancel();googleWaiting=false;updateAuthControls();$('accountCancel').hidden=true;$('accountError').textContent='';};
  function showCode(pending=false){sendAfter=pending?0:Date.now()+60000;$('loginPassword').value='';$('accountEntry').hidden=true;$('accountVerifyForm').hidden=false;$('accountCodeHint').textContent=pending?'Your email is not confirmed yet. Use Resend code to request a new verification email.':'Check '+$('loginEmail').value+' for your six-digit code. If you already have an account, choose Sign in instead.';$('loginCode').focus();updateAuthControls();}
  async function sendCode(){await window.api.accountSendCode($('loginEmail').value);confirmation=false;showCode();}
  $('accountSendCode').onclick=()=>{if($('loginEmail').reportValidity())action($('accountSendCode'),sendCode);};
  $('accountSwitchMode').onclick=()=>{authMode=authMode==='signup'?'signin':'signup';$('loginPassword').value='';$('accountError').textContent='';$('accountTitle').textContent=authMode==='signup'?'Create your account':'Welcome to AetherAI';updateAuthControls();};
  $('accountEmailForm').onsubmit=e=>{e.preventDefault();action($('accountSubmit'),async()=>{const password=$('loginPassword').value;try{const result=await (authMode==='signup'?window.api.accountSignUp:window.api.accountSignIn)($('loginEmail').value,password);if(result.existingAccountPossible)throw Error('This email may already have an account. Choose Sign in or Continue with Google instead of registering again.');if(result.confirmationRequired){confirmation=true;showCode(result.confirmationPending===true);}else{account=result;render();if(account.user)close(accountModal);}}finally{$('loginPassword').value='';}});};
  $('accountResend').onclick=()=>action($('accountResend'),async()=>{if(confirmation){await window.api.accountResendConfirmation($('loginEmail').value);showCode();}else await sendCode();});
  $('accountBack').onclick=()=>{$('accountVerifyForm').hidden=true;$('accountEntry').hidden=false;$('loginCode').value='';$('accountError').textContent='';$('loginEmail').focus();};
  $('accountVerifyForm').onsubmit=e=>{e.preventDefault();action($('accountVerifyCode'),async()=>{account=await window.api.accountVerify($('loginEmail').value,$('loginCode').value);$('loginCode').value='';$('accountVerifyForm').hidden=true;$('accountEntry').hidden=false;render();if(account.user)close(accountModal);});};
  $('accountLogout').onclick=()=>action($('accountLogout'),async()=>{account=await window.api.accountLogout();googleWaiting=false;render();});
  window.api?.onAccountChanged?.(async value=>{googleWaiting=false;if(value.error)$('accountError').textContent=value.error;else {account=value;render();$('accountError').textContent='';if(account.user)close(accountModal);}$('accountCancel').hidden=true;updateAuthControls();});
  async function renderMemory(){const entries=await window.api.memoryList();const list=$('memoryList');list.replaceChildren();for(const entry of entries){const row=document.createElement('article');row.className='memory-entry';const text=document.createElement('p');text.textContent=entry.content;const scope=document.createElement('small');scope.textContent='Response preferences';const controls=document.createElement('div');
      const enabled=document.createElement('button');enabled.type='button';enabled.textContent=entry.enabled?'Enabled':'Disabled';enabled.setAttribute('aria-pressed',String(entry.enabled));enabled.onclick=async()=>{await window.api.memorySave({...entry,enabled:!entry.enabled});await renderMemory();};
      const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>{editing=entry.id;$('memoryText').value=entry.content;$('memoryText').focus();};
      const remove=document.createElement('button');remove.type='button';remove.textContent='Delete';remove.onclick=async()=>{await window.api.memoryRemove(entry.id);if(editing===entry.id){editing=null;$('memoryText').value='';}await renderMemory();};
      controls.append(enabled,edit,remove);row.append(scope,text,controls);list.append(row);
    }if(!entries.length){const empty=document.createElement('p');empty.textContent='No presets yet.';list.append(empty);}}
  $('openMemory').onclick=async()=>{close(accountModal);await refresh();try{await renderMemory();$('memoryError').textContent='';}catch(e){$('memoryError').textContent=e.message;}memoryModal.classList.add('show');$('memoryText').focus();};
  $('memoryForm').onsubmit=async e=>{e.preventDefault();try{await window.api.memorySave({id:editing,content:$('memoryText').value,projectId:null,enabled:true});editing=null;$('memoryText').value='';$('memoryError').textContent='';await renderMemory();}catch(e){$('memoryError').textContent=e.message;}};
  $('memoryCancelEdit').onclick=()=>{editing=null;$('memoryText').value='';};
  $('memorySync').onclick=async()=>{const button=$('memorySync');button.disabled=true;try{await window.api.memorySync();await renderMemory();$('memoryError').textContent='Presets synced.';}catch(e){$('memoryError').textContent=e.message;}finally{render();}};
  window.AetherAIAccount={setProjects(value){projects=value.map(p=>({id:p.id,name:p.name||p.title||'Project'}));},setModel(value){if(activeModel?.name!==value?.name)useMemory.checked=false;activeModel=value;useMemory.disabled=!value;consentText.textContent=value?'Use presets in chats. '+(value.name.startsWith('cloud:')?'Enabled presets will be sent to '+(value.provider||'Ollama Cloud')+' / '+(value.cloudName||value.name)+'.':'Enabled presets will be used by the local model '+value.name+'.'):'Choose a model before enabling presets in chats.';},async context(projectId,modelName){if(!useMemory.checked||activeModel?.name!==modelName)return '';return await window.api?.memoryContext?.(projectId)||'';}};
  refresh().then(()=>{accountModal.dataset.loading='false';if(account.user)close(accountModal);else openAccount(true);}).catch(()=>{accountModal.dataset.loading='false';render();openAccount(true);$('accountError').textContent='Could not load your account. You can continue without signing in.';});
})();
